apiVersion: v1
kind: Namespace
metadata:
  name: test-ns
  labels:
    environmentId: env_727df10a-f6fb-4f8f-9caf-e77e5e21ca8d
    projectId: project_933dc7e0-827d-4fe9-8614-9e7c3f22f7a7
    projectName: test1
    environmentName: new-env
    organizationId: org_3fe5a754-9f2c-48a1-a0cf-5e307ff42d78
